services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: edu_php
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: edu_postgres
    environment:
      POSTGRES_DB: edu_platform
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  nginx:
    image: nginx:latest
    container_name: edu_nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
    depends_on:
      - php

volumes:
  pgdata: